# Generated by Django 3.0.8 on 2020-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200704_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.CharField(max_length=100, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.CharField(max_length=100, verbose_name='Longitude'),
        ),
    ]
